### ISSUE TITLE
[enhancement] More info

### ISSUE THREAD

**Issue by ahinojos0029** [ey3tech/vertigo#4]
If you could please add some more information (and examples if you can) about all the commands. For right now you are just saying what the commands ARE and not saying what the commands DO.

**Comment by ahinojos0029** [comment]
Actually just need examples that all

**Comment by thrzl** [comment]
Could you elaborate on this a bit? Not sure I understand completely, are you saying that the commands don't tell you how to use them?

**Comment by ahinojos0029** [comment]
I'm just saying that you need to describe more and actually show examples. And yes, the commands don't really tell you how to use them

**Comment by thrzl** [comment]
Running `vertigo [command] -h` will show you a help menu with the command's options and a short description of them:
![image](https://user-images.githubusercontent.com/73202594/159588803-943735d9-6af7-4ba6-b293-29019c69624d.png)

**Comment by ahinojos0029** [comment]
I was thinking of maybe examples of the brute command.

**Comment by thrzl** [comment]
The brute command is heavily WIP, I don't think it would work at all

**Comment by ahinojos0029** [comment]
I think it would be best to just explain what the commands do more. maybe explain the usage a bit more too
